import type { Metadata } from "next";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import QueryClientLayout from "@/components/layouts/query-client-provider";
import SileoLayout from "@/components/layouts/sileo-layout";
import MantineUIProvider from "@/core/infrastructure/providers/mantine-provider";
import ModalProvider from "@/core/infrastructure/providers/modal-provider";

export const metadata: Metadata = {
  title: "Albergue Salva Vidas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <head></head>
      <body className="min-h-full flex flex-col">
        <QueryClientLayout>
          <SileoLayout>
            <MantineUIProvider>
              <ModalProvider>
                {children}
                <SpeedInsights />
              </ModalProvider>
            </MantineUIProvider>
          </SileoLayout>
        </QueryClientLayout>
      </body>
    </html>
  );
}
