--
-- PostgreSQL database dump
--



-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.11 (Ubuntu 17.11-1.pgdg24.04+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AdoptionFollowUps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AdoptionFollowUps" (
    "Id" integer NOT NULL,
    "AdoptionId" integer NOT NULL,
    "FollowUpDate" timestamp with time zone NOT NULL,
    "Type" text NOT NULL,
    "Status" text NOT NULL,
    "Title" text NOT NULL,
    "Notes" character varying(1000) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: AdoptionFollowUps_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AdoptionFollowUps" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AdoptionFollowUps_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Adoptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Adoptions" (
    "Id" integer NOT NULL,
    "RequestAdoptionId" integer NOT NULL,
    "AdoptionDate" timestamp with time zone NOT NULL,
    "Status" text NOT NULL,
    "Observations" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: Adoptions_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Adoptions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Adoptions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AuditLogs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AuditLogs" (
    "Id" integer NOT NULL,
    "UserId" uuid,
    "AuditType" text NOT NULL,
    "TableName" character varying(100) NOT NULL,
    "RecordId" text NOT NULL,
    "OldValues" text,
    "CreatedAt" timestamp with time zone NOT NULL
);


--
-- Name: AuditLogs_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AuditLogs" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AuditLogs_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Breeds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Breeds" (
    "Id" uuid NOT NULL,
    "Name" character varying(80) NOT NULL,
    "SpeciesId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: DonationFollowUps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."DonationFollowUps" (
    "Id" integer NOT NULL,
    "DonationId" integer NOT NULL,
    "FollowUpDate" timestamp with time zone NOT NULL,
    "IsPaid" boolean DEFAULT false NOT NULL,
    "Notes" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: DonationFollowUps_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."DonationFollowUps" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."DonationFollowUps_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Donations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Donations" (
    "Id" integer NOT NULL,
    "RequestDonationId" integer NOT NULL,
    "DonationDate" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: Donations_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Donations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Donations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: EmailVerifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."EmailVerifications" (
    "Id" uuid NOT NULL,
    "Email" text NOT NULL,
    "VerificationCode" text NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "IsVerified" boolean NOT NULL,
    "Attempts" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: Events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Events" (
    "Id" integer NOT NULL,
    "Title" character varying(200) NOT NULL,
    "SubTitle" text,
    "Description" character varying(2000),
    "ToDo" text,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "ImageUrl" text,
    "BannerUrl" character varying(500),
    "VideoUrl" text,
    "VideoSilenceUrl" text,
    "IsActive" boolean NOT NULL,
    "IsFeatured" boolean NOT NULL,
    "GoogleAddressLink" text,
    "Location" character varying(500) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: Events_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Events" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Events_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Givings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Givings" (
    "Id" integer NOT NULL,
    "Amount" numeric(10,2),
    "Name" character varying(150) NOT NULL,
    "Type" text NOT NULL,
    "Quantity" numeric(10,2),
    "Unit" text,
    "Kg" numeric(10,2),
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: Givings_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Givings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Givings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: MedicalRecords; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."MedicalRecords" (
    "Id" uuid NOT NULL,
    "PetId" uuid NOT NULL,
    "VisitDate" timestamp with time zone NOT NULL,
    "Diagnosis" character varying(500) NOT NULL,
    "Treatment" character varying(1000),
    "Notes" character varying(1000),
    "RequiresFollowUp" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: PaymentHistories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."PaymentHistories" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Currency" character varying(3) DEFAULT 'PEN'::character varying NOT NULL,
    "Status" text NOT NULL,
    "Provider" character varying(50) NOT NULL,
    "TransactionId" character varying(255),
    "RawResponse" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: Permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Permissions" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Module" character varying(100) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: PetBreeds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."PetBreeds" (
    "Id" uuid NOT NULL,
    "PetId" uuid NOT NULL,
    "BreedId" uuid NOT NULL,
    "BreedId1" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: PetPhotos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."PetPhotos" (
    "Id" uuid NOT NULL,
    "Url" character varying(500) NOT NULL,
    "IsMain" boolean NOT NULL,
    "PetId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: PetSponsors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."PetSponsors" (
    "UserId" uuid NOT NULL,
    "PetId" uuid NOT NULL,
    "MonthlyAmount" numeric(18,2) NOT NULL,
    "Status" text NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone,
    "Notes" character varying(500),
    "Id" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: PetTraits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."PetTraits" (
    "Id" uuid NOT NULL,
    "PetId" uuid NOT NULL,
    "TraitId" uuid NOT NULL,
    "TraitId1" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: PetVaccines; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."PetVaccines" (
    "Id" uuid NOT NULL,
    "PetId" uuid NOT NULL,
    "VaccineId" uuid NOT NULL,
    "AppliedDate" timestamp with time zone NOT NULL,
    "ExpirationDate" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: Pets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Pets" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "RescueStory" character varying(1000),
    "BirthDate" date,
    "WeightKg" numeric(5,2),
    "Slug" text NOT NULL,
    "IsVaccinated" boolean NOT NULL,
    "IsRecommend" boolean,
    "IsSterilized" boolean NOT NULL,
    "IsAdopted" boolean NOT NULL,
    "Age" integer NOT NULL,
    "Gender" character varying(20) NOT NULL,
    "Size" character varying(20) NOT NULL,
    "Status" character varying(30) NOT NULL,
    "SpeciesId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: PricingDonations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."PricingDonations" (
    "Id" integer NOT NULL,
    "GivingId" integer NOT NULL,
    "Title" character varying(150) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "Benefits" character varying(1000),
    "IsFeatured" boolean DEFAULT false NOT NULL,
    "IsActive" boolean DEFAULT true NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: PricingDonations_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."PricingDonations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PricingDonations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PricingSponsors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."PricingSponsors" (
    "Id" integer NOT NULL,
    "Name" character varying(150) NOT NULL,
    "Description" character varying(500),
    "GivingId" integer NOT NULL,
    "IsRelevant" boolean DEFAULT false NOT NULL,
    "IsActive" boolean DEFAULT true NOT NULL,
    "Benefits" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: PricingSponsors_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."PricingSponsors" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PricingSponsors_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: RequestAdoptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."RequestAdoptions" (
    "Id" integer NOT NULL,
    "UserId" uuid NOT NULL,
    "PetId" uuid,
    "HouseType" character varying(100) NOT NULL,
    "HasOtherPets" boolean DEFAULT false NOT NULL,
    "HasChildren" boolean DEFAULT false NOT NULL,
    "AcceptHomeVisit" boolean DEFAULT false NOT NULL,
    "ReviewedAt" timestamp with time zone,
    "ReviewedBy" uuid,
    "ReviewComment" character varying(1000),
    "Dni" character varying(8) NOT NULL,
    "PlatformProvider" text DEFAULT 'Web'::text NOT NULL,
    "Status" character varying(50) NOT NULL,
    "Motivation" character varying(1000) NOT NULL,
    "District" character varying(100) NOT NULL,
    "Phone" character varying(20) NOT NULL,
    "Address" character varying(200) NOT NULL,
    "Reference" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: RequestAdoptions_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."RequestAdoptions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."RequestAdoptions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: RequestDonations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."RequestDonations" (
    "Id" integer NOT NULL,
    "UserId" uuid NOT NULL,
    "Message" character varying(1000),
    "Status" character varying(50) NOT NULL,
    "ReviewedAt" timestamp with time zone,
    "ReviewedBy" uuid,
    "Provider" character varying(50) NOT NULL,
    "ReviewComment" character varying(1000),
    "PlanDonationId" integer,
    "IsMonthly" boolean DEFAULT false NOT NULL,
    "IsYearly" boolean DEFAULT false NOT NULL,
    "IsOneTime" boolean DEFAULT true NOT NULL,
    "Amount" numeric(10,2) NOT NULL,
    "Address" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: RequestDonations_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."RequestDonations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."RequestDonations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: RequestSponsors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."RequestSponsors" (
    "Id" integer NOT NULL,
    "UserId" uuid NOT NULL,
    "PetId" uuid NOT NULL,
    "PlanSponsorId" integer NOT NULL,
    "Message" character varying(1000),
    "Status" text DEFAULT 'PENDIENTE'::text NOT NULL,
    "Provider" integer NOT NULL,
    "Mode" text DEFAULT 'MENSUAL'::text NOT NULL,
    "ReviewedAt" timestamp with time zone,
    "ReviewedBy" uuid,
    "ReviewComment" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: RequestSponsors_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."RequestSponsors" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."RequestSponsors_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: RequestVolunteers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."RequestVolunteers" (
    "Id" integer NOT NULL,
    "VolunteerApplicationId" integer NOT NULL,
    "RequestDate" timestamp with time zone NOT NULL,
    "Status" character varying(50) NOT NULL,
    "UserId" uuid NOT NULL,
    "Message" character varying(1000),
    "ReviewedAt" timestamp with time zone,
    "ReviewedBy" uuid,
    "ReviewComment" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: RequestVolunteers_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."RequestVolunteers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."RequestVolunteers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: RolePermissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."RolePermissions" (
    "RoleId" uuid NOT NULL,
    "PermissionId" uuid NOT NULL,
    "Id" integer NOT NULL
);


--
-- Name: Roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Roles" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(250),
    "NotDelete" boolean NOT NULL,
    "ToDashboard" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: Species; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Species" (
    "Id" uuid NOT NULL,
    "Name" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: SponsorFollowUps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."SponsorFollowUps" (
    "Id" integer NOT NULL,
    "SponsorId" integer NOT NULL,
    "FollowUpDate" timestamp with time zone NOT NULL,
    "IsPaid" boolean NOT NULL,
    "Notes" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: SponsorFollowUps_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."SponsorFollowUps" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SponsorFollowUps_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Sponsors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Sponsors" (
    "Id" integer NOT NULL,
    "RequestSponsorId" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: Sponsors_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Sponsors" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Sponsors_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Traits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Traits" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Users" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "Password" character varying(255) NOT NULL,
    "Dni" character varying(20),
    "Ruc" character varying(20),
    "Phone" character varying(20),
    "District" character varying(100),
    "RoleId" uuid NOT NULL,
    "IsBlocked" boolean,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: Vacines; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Vacines" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: VolunteerApplications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."VolunteerApplications" (
    "Id" integer NOT NULL,
    "Title" character varying(200) NOT NULL,
    "SubTitle" character varying(300),
    "Description" character varying(5000) NOT NULL,
    "Requirements" character varying(1000),
    "MinAge" integer,
    "MaxAge" integer,
    "Address" character varying(200),
    "GoogleMapLinkAddress" character varying(1000),
    "StartDate" timestamp with time zone,
    "EndDate" timestamp with time zone,
    "ContactEmail" character varying(100),
    "ContactPhone" character varying(20),
    "IsCertified" boolean DEFAULT false NOT NULL,
    "Urgency" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: VolunteerApplications_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."VolunteerApplications" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."VolunteerApplications_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Volunteers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Volunteers" (
    "Id" integer NOT NULL,
    "RequestVolunteerId" integer NOT NULL,
    "ApplicationDate" timestamp with time zone NOT NULL,
    "ExpiredDate" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "LastUpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" uuid
);


--
-- Name: Volunteers_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Volunteers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Volunteers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Data for Name: AdoptionFollowUps; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."AdoptionFollowUps" ("Id", "AdoptionId", "FollowUpDate", "Type", "Status", "Title", "Notes", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: Adoptions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Adoptions" ("Id", "RequestAdoptionId", "AdoptionDate", "Status", "Observations", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: AuditLogs; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."AuditLogs" ("Id", "UserId", "AuditType", "TableName", "RecordId", "OldValues", "CreatedAt") FROM stdin;
\.


--
-- Data for Name: Breeds; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Breeds" ("Id", "Name", "SpeciesId", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: DonationFollowUps; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."DonationFollowUps" ("Id", "DonationId", "FollowUpDate", "IsPaid", "Notes", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: Donations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Donations" ("Id", "RequestDonationId", "DonationDate", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: EmailVerifications; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."EmailVerifications" ("Id", "Email", "VerificationCode", "ExpiresAt", "IsVerified", "Attempts", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: Events; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Events" ("Id", "Title", "SubTitle", "Description", "ToDo", "StartDate", "EndDate", "ImageUrl", "BannerUrl", "VideoUrl", "VideoSilenceUrl", "IsActive", "IsFeatured", "GoogleAddressLink", "Location", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: Givings; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Givings" ("Id", "Amount", "Name", "Type", "Quantity", "Unit", "Kg", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: MedicalRecords; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."MedicalRecords" ("Id", "PetId", "VisitDate", "Diagnosis", "Treatment", "Notes", "RequiresFollowUp", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: PaymentHistories; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."PaymentHistories" ("Id", "UserId", "Amount", "Currency", "Status", "Provider", "TransactionId", "RawResponse", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: Permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Permissions" ("Id", "Name", "Module", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
0e7737d6-b0c1-428d-ab73-b4f20198b3c2	Donaciones	Donaciones	2026-05-26 14:26:57.834969+00	\N	2026-05-26 14:26:57.83497+00	\N
276a5e30-3355-4687-bef8-477b7e5970d7	Voluntarios	Voluntarios	2026-05-26 14:26:46.566582+00	\N	2026-05-26 14:26:46.566582+00	\N
809341ae-31fa-45bb-9052-9e81d8ac5bdd	Albergue	Albergue	2026-05-26 14:26:07.668298+00	\N	2026-05-26 14:26:07.668299+00	\N
897b16eb-36a6-429a-adeb-7dda6682b8a2	Adopciones	Adopciones	2026-05-26 14:26:17.755037+00	\N	2026-05-26 14:26:17.755038+00	\N
dc94de38-3eab-4f2e-8065-871e18f4a288	Organizacion	Organizacion	2026-05-26 14:25:53.799625+00	\N	2026-05-26 14:25:53.799709+00	\N
f75bb2c6-6f99-4423-aa78-106974f68786	Padrinos	Padrinos	2026-05-26 14:26:31.514209+00	\N	2026-05-26 14:26:31.514209+00	\N
\.


--
-- Data for Name: PetBreeds; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."PetBreeds" ("Id", "PetId", "BreedId", "BreedId1", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: PetPhotos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."PetPhotos" ("Id", "Url", "IsMain", "PetId", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: PetSponsors; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."PetSponsors" ("UserId", "PetId", "MonthlyAmount", "Status", "StartDate", "EndDate", "Notes", "Id", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: PetTraits; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."PetTraits" ("Id", "PetId", "TraitId", "TraitId1", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: PetVaccines; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."PetVaccines" ("Id", "PetId", "VaccineId", "AppliedDate", "ExpirationDate", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: Pets; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Pets" ("Id", "Name", "Description", "RescueStory", "BirthDate", "WeightKg", "Slug", "IsVaccinated", "IsRecommend", "IsSterilized", "IsAdopted", "Age", "Gender", "Size", "Status", "SpeciesId", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: PricingDonations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."PricingDonations" ("Id", "GivingId", "Title", "Description", "Benefits", "IsFeatured", "IsActive", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: PricingSponsors; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."PricingSponsors" ("Id", "Name", "Description", "GivingId", "IsRelevant", "IsActive", "Benefits", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: RequestAdoptions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."RequestAdoptions" ("Id", "UserId", "PetId", "HouseType", "HasOtherPets", "HasChildren", "AcceptHomeVisit", "ReviewedAt", "ReviewedBy", "ReviewComment", "Dni", "PlatformProvider", "Status", "Motivation", "District", "Phone", "Address", "Reference", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: RequestDonations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."RequestDonations" ("Id", "UserId", "Message", "Status", "ReviewedAt", "ReviewedBy", "Provider", "ReviewComment", "PlanDonationId", "IsMonthly", "IsYearly", "IsOneTime", "Amount", "Address", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: RequestSponsors; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."RequestSponsors" ("Id", "UserId", "PetId", "PlanSponsorId", "Message", "Status", "Provider", "Mode", "ReviewedAt", "ReviewedBy", "ReviewComment", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: RequestVolunteers; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."RequestVolunteers" ("Id", "VolunteerApplicationId", "RequestDate", "Status", "UserId", "Message", "ReviewedAt", "ReviewedBy", "ReviewComment", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: RolePermissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."RolePermissions" ("RoleId", "PermissionId", "Id") FROM stdin;
003583c1-414b-4ccb-8a6a-a4b8789e1a19	f75bb2c6-6f99-4423-aa78-106974f68786	0
1e31b87f-b26d-40b9-a342-c77dc496d0f6	0e7737d6-b0c1-428d-ab73-b4f20198b3c2	0
1e31b87f-b26d-40b9-a342-c77dc496d0f6	276a5e30-3355-4687-bef8-477b7e5970d7	0
1e31b87f-b26d-40b9-a342-c77dc496d0f6	809341ae-31fa-45bb-9052-9e81d8ac5bdd	0
1e31b87f-b26d-40b9-a342-c77dc496d0f6	897b16eb-36a6-429a-adeb-7dda6682b8a2	0
1e31b87f-b26d-40b9-a342-c77dc496d0f6	dc94de38-3eab-4f2e-8065-871e18f4a288	0
1e31b87f-b26d-40b9-a342-c77dc496d0f6	f75bb2c6-6f99-4423-aa78-106974f68786	0
\.


--
-- Data for Name: Roles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Roles" ("Id", "Name", "Description", "NotDelete", "ToDashboard", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
003583c1-414b-4ccb-8a6a-a4b8789e1a19	EMPLEADO		f	t	2026-05-27 13:03:31.032294+00	\N	2026-05-27 13:03:31.032295+00	\N
1ae2d0b0-03c9-46cd-ab85-2ace6818de42	DONADOR	\N	t	f	2026-05-24 20:55:36+00	\N	2026-05-24 20:55:38+00	\N
1e31b87f-b26d-40b9-a342-c77dc496d0f6	ADMINISTRADOR		f	t	2026-05-24 20:54:16+00	\N	2026-06-03 00:53:52.59686+00	\N
41ea394c-8273-473d-8829-be0a2811109c	USUARIOS	\N	t	f	2026-05-24 20:53:36+00	\N	2026-05-24 20:53:40+00	\N
68e1a561-9e65-4051-aa8b-17226be09c60	PADRINO	\N	t	f	2026-05-24 20:55:13+00	\N	2026-05-24 20:55:16+00	\N
ac962ce0-ef1f-428e-9eec-574026465b67	VOLUNTARIO	\N	t	f	2026-05-24 20:54:46+00	\N	2026-05-24 20:54:49+00	\N
\.


--
-- Data for Name: Species; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Species" ("Id", "Name", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: SponsorFollowUps; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."SponsorFollowUps" ("Id", "SponsorId", "FollowUpDate", "IsPaid", "Notes", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: Sponsors; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Sponsors" ("Id", "RequestSponsorId", "StartDate", "EndDate", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: Traits; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Traits" ("Id", "Name", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Users" ("Id", "Name", "LastName", "Email", "Password", "Dni", "Ruc", "Phone", "District", "RoleId", "IsBlocked", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
d0da3940-7778-4457-bd80-162617adf2db	Administrador	I	administrador@alberguesalvavidas.com	$2a$11$qQCac1MefWaQzD0PaNfn2.MywQnXEHL8JkGfpcgnrgUcb9UQ.YY66	\N	\N	\N	\N	1e31b87f-b26d-40b9-a342-c77dc496d0f6	\N	2026-05-24 20:56:40+00	\N	2026-05-24 20:56:43+00	\N
\.


--
-- Data for Name: Vacines; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Vacines" ("Id", "Name", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: VolunteerApplications; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."VolunteerApplications" ("Id", "Title", "SubTitle", "Description", "Requirements", "MinAge", "MaxAge", "Address", "GoogleMapLinkAddress", "StartDate", "EndDate", "ContactEmail", "ContactPhone", "IsCertified", "Urgency", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: Volunteers; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Volunteers" ("Id", "RequestVolunteerId", "ApplicationDate", "ExpiredDate", "CreatedAt", "CreatedBy", "LastUpdatedAt", "UpdatedBy") FROM stdin;
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260903004052_Initial	10.0.7
\.


--
-- Name: AdoptionFollowUps_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."AdoptionFollowUps_Id_seq"', 1, false);


--
-- Name: Adoptions_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Adoptions_Id_seq"', 1, false);


--
-- Name: AuditLogs_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."AuditLogs_Id_seq"', 1, false);


--
-- Name: DonationFollowUps_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."DonationFollowUps_Id_seq"', 1, false);


--
-- Name: Donations_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Donations_Id_seq"', 1, false);


--
-- Name: Events_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Events_Id_seq"', 1, false);


--
-- Name: Givings_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Givings_Id_seq"', 1, false);


--
-- Name: PricingDonations_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."PricingDonations_Id_seq"', 1, false);


--
-- Name: PricingSponsors_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."PricingSponsors_Id_seq"', 1, false);


--
-- Name: RequestAdoptions_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."RequestAdoptions_Id_seq"', 1, false);


--
-- Name: RequestDonations_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."RequestDonations_Id_seq"', 1, false);


--
-- Name: RequestSponsors_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."RequestSponsors_Id_seq"', 1, false);


--
-- Name: RequestVolunteers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."RequestVolunteers_Id_seq"', 1, false);


--
-- Name: SponsorFollowUps_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."SponsorFollowUps_Id_seq"', 1, false);


--
-- Name: Sponsors_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Sponsors_Id_seq"', 1, false);


--
-- Name: VolunteerApplications_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."VolunteerApplications_Id_seq"', 1, false);


--
-- Name: Volunteers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Volunteers_Id_seq"', 1, false);


--
-- Name: AdoptionFollowUps PK_AdoptionFollowUps; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AdoptionFollowUps"
    ADD CONSTRAINT "PK_AdoptionFollowUps" PRIMARY KEY ("Id");


--
-- Name: Adoptions PK_Adoptions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Adoptions"
    ADD CONSTRAINT "PK_Adoptions" PRIMARY KEY ("Id");


--
-- Name: AuditLogs PK_AuditLogs; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AuditLogs"
    ADD CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id");


--
-- Name: Breeds PK_Breeds; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Breeds"
    ADD CONSTRAINT "PK_Breeds" PRIMARY KEY ("Id");


--
-- Name: DonationFollowUps PK_DonationFollowUps; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DonationFollowUps"
    ADD CONSTRAINT "PK_DonationFollowUps" PRIMARY KEY ("Id");


--
-- Name: Donations PK_Donations; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Donations"
    ADD CONSTRAINT "PK_Donations" PRIMARY KEY ("Id");


--
-- Name: EmailVerifications PK_EmailVerifications; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."EmailVerifications"
    ADD CONSTRAINT "PK_EmailVerifications" PRIMARY KEY ("Id");


--
-- Name: Events PK_Events; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Events"
    ADD CONSTRAINT "PK_Events" PRIMARY KEY ("Id");


--
-- Name: Givings PK_Givings; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Givings"
    ADD CONSTRAINT "PK_Givings" PRIMARY KEY ("Id");


--
-- Name: MedicalRecords PK_MedicalRecords; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MedicalRecords"
    ADD CONSTRAINT "PK_MedicalRecords" PRIMARY KEY ("Id");


--
-- Name: PaymentHistories PK_PaymentHistories; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PaymentHistories"
    ADD CONSTRAINT "PK_PaymentHistories" PRIMARY KEY ("Id");


--
-- Name: Permissions PK_Permissions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Permissions"
    ADD CONSTRAINT "PK_Permissions" PRIMARY KEY ("Id");


--
-- Name: PetBreeds PK_PetBreeds; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PetBreeds"
    ADD CONSTRAINT "PK_PetBreeds" PRIMARY KEY ("Id");


--
-- Name: PetPhotos PK_PetPhotos; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PetPhotos"
    ADD CONSTRAINT "PK_PetPhotos" PRIMARY KEY ("Id");


--
-- Name: PetSponsors PK_PetSponsors; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PetSponsors"
    ADD CONSTRAINT "PK_PetSponsors" PRIMARY KEY ("UserId", "PetId");


--
-- Name: PetTraits PK_PetTraits; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PetTraits"
    ADD CONSTRAINT "PK_PetTraits" PRIMARY KEY ("Id");


--
-- Name: PetVaccines PK_PetVaccines; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PetVaccines"
    ADD CONSTRAINT "PK_PetVaccines" PRIMARY KEY ("Id");


--
-- Name: Pets PK_Pets; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Pets"
    ADD CONSTRAINT "PK_Pets" PRIMARY KEY ("Id");


--
-- Name: PricingDonations PK_PricingDonations; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PricingDonations"
    ADD CONSTRAINT "PK_PricingDonations" PRIMARY KEY ("Id");


--
-- Name: PricingSponsors PK_PricingSponsors; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PricingSponsors"
    ADD CONSTRAINT "PK_PricingSponsors" PRIMARY KEY ("Id");


--
-- Name: RequestAdoptions PK_RequestAdoptions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RequestAdoptions"
    ADD CONSTRAINT "PK_RequestAdoptions" PRIMARY KEY ("Id");


--
-- Name: RequestDonations PK_RequestDonations; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RequestDonations"
    ADD CONSTRAINT "PK_RequestDonations" PRIMARY KEY ("Id");


--
-- Name: RequestSponsors PK_RequestSponsors; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RequestSponsors"
    ADD CONSTRAINT "PK_RequestSponsors" PRIMARY KEY ("Id");


--
-- Name: RequestVolunteers PK_RequestVolunteers; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RequestVolunteers"
    ADD CONSTRAINT "PK_RequestVolunteers" PRIMARY KEY ("Id");


--
-- Name: RolePermissions PK_RolePermissions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RolePermissions"
    ADD CONSTRAINT "PK_RolePermissions" PRIMARY KEY ("RoleId", "PermissionId");


--
-- Name: Roles PK_Roles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Roles"
    ADD CONSTRAINT "PK_Roles" PRIMARY KEY ("Id");


--
-- Name: Species PK_Species; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Species"
    ADD CONSTRAINT "PK_Species" PRIMARY KEY ("Id");


--
-- Name: SponsorFollowUps PK_SponsorFollowUps; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SponsorFollowUps"
    ADD CONSTRAINT "PK_SponsorFollowUps" PRIMARY KEY ("Id");


--
-- Name: Sponsors PK_Sponsors; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Sponsors"
    ADD CONSTRAINT "PK_Sponsors" PRIMARY KEY ("Id");


--
-- Name: Traits PK_Traits; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Traits"
    ADD CONSTRAINT "PK_Traits" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: Vacines PK_Vacines; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Vacines"
    ADD CONSTRAINT "PK_Vacines" PRIMARY KEY ("Id");


--
-- Name: VolunteerApplications PK_VolunteerApplications; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."VolunteerApplications"
    ADD CONSTRAINT "PK_VolunteerApplications" PRIMARY KEY ("Id");


--
-- Name: Volunteers PK_Volunteers; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Volunteers"
    ADD CONSTRAINT "PK_Volunteers" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_AdoptionFollowUps_AdoptionId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AdoptionFollowUps_AdoptionId" ON public."AdoptionFollowUps" USING btree ("AdoptionId");


--
-- Name: IX_AdoptionFollowUps_AdoptionId_FollowUpDate; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AdoptionFollowUps_AdoptionId_FollowUpDate" ON public."AdoptionFollowUps" USING btree ("AdoptionId", "FollowUpDate");


--
-- Name: IX_AdoptionFollowUps_FollowUpDate; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AdoptionFollowUps_FollowUpDate" ON public."AdoptionFollowUps" USING btree ("FollowUpDate");


--
-- Name: IX_Adoptions_AdoptionDate; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Adoptions_AdoptionDate" ON public."Adoptions" USING btree ("AdoptionDate");


--
-- Name: IX_Adoptions_RequestAdoptionId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Adoptions_RequestAdoptionId" ON public."Adoptions" USING btree ("RequestAdoptionId");


--
-- Name: IX_AuditLogs_TableName_RecordId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AuditLogs_TableName_RecordId" ON public."AuditLogs" USING btree ("TableName", "RecordId");


--
-- Name: IX_AuditLogs_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AuditLogs_UserId" ON public."AuditLogs" USING btree ("UserId");


--
-- Name: IX_Breeds_SpeciesId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Breeds_SpeciesId" ON public."Breeds" USING btree ("SpeciesId");


--
-- Name: IX_DonationFollowUps_DonationId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DonationFollowUps_DonationId" ON public."DonationFollowUps" USING btree ("DonationId");


--
-- Name: IX_DonationFollowUps_DonationId_FollowUpDate; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DonationFollowUps_DonationId_FollowUpDate" ON public."DonationFollowUps" USING btree ("DonationId", "FollowUpDate");


--
-- Name: IX_DonationFollowUps_FollowUpDate; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DonationFollowUps_FollowUpDate" ON public."DonationFollowUps" USING btree ("FollowUpDate");


--
-- Name: IX_DonationFollowUps_IsPaid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DonationFollowUps_IsPaid" ON public."DonationFollowUps" USING btree ("IsPaid");


--
-- Name: IX_Donations_DonationDate; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Donations_DonationDate" ON public."Donations" USING btree ("DonationDate");


--
-- Name: IX_Donations_RequestDonationId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Donations_RequestDonationId" ON public."Donations" USING btree ("RequestDonationId");


--
-- Name: IX_Donations_RequestDonationId_DonationDate; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Donations_RequestDonationId_DonationDate" ON public."Donations" USING btree ("RequestDonationId", "DonationDate");


--
-- Name: IX_MedicalRecords_PetId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_MedicalRecords_PetId" ON public."MedicalRecords" USING btree ("PetId");


--
-- Name: IX_PaymentHistories_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_PaymentHistories_UserId" ON public."PaymentHistories" USING btree ("UserId");


--
-- Name: IX_Permissions_Module_Name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Permissions_Module_Name" ON public."Permissions" USING btree ("Module", "Name");


--
-- Name: IX_PetBreeds_BreedId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_PetBreeds_BreedId" ON public."PetBreeds" USING btree ("BreedId");


--
-- Name: IX_PetBreeds_BreedId1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_PetBreeds_BreedId1" ON public."PetBreeds" USING btree ("BreedId1");


--
-- Name: IX_PetBreeds_PetId_BreedId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_PetBreeds_PetId_BreedId" ON public."PetBreeds" USING btree ("PetId", "BreedId");


--
-- Name: IX_PetPhotos_PetId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_PetPhotos_PetId" ON public."PetPhotos" USING btree ("PetId");


--
-- Name: IX_PetSponsors_PetId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_PetSponsors_PetId" ON public."PetSponsors" USING btree ("PetId");


--
-- Name: IX_PetTraits_PetId_TraitId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_PetTraits_PetId_TraitId" ON public."PetTraits" USING btree ("PetId", "TraitId");


--
-- Name: IX_PetTraits_TraitId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_PetTraits_TraitId" ON public."PetTraits" USING btree ("TraitId");


--
-- Name: IX_PetTraits_TraitId1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_PetTraits_TraitId1" ON public."PetTraits" USING btree ("TraitId1");


--
-- Name: IX_PetVaccines_PetId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_PetVaccines_PetId" ON public."PetVaccines" USING btree ("PetId");


--
-- Name: IX_PetVaccines_VaccineId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_PetVaccines_VaccineId" ON public."PetVaccines" USING btree ("VaccineId");


--
-- Name: IX_Pets_Slug; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Pets_Slug" ON public."Pets" USING btree ("Slug");


--
-- Name: IX_Pets_SpeciesId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Pets_SpeciesId" ON public."Pets" USING btree ("SpeciesId");


--
-- Name: IX_PricingDonations_GivingId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_PricingDonations_GivingId" ON public."PricingDonations" USING btree ("GivingId");


--
-- Name: IX_PricingDonations_IsActive; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_PricingDonations_IsActive" ON public."PricingDonations" USING btree ("IsActive");


--
-- Name: IX_PricingDonations_IsFeatured; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_PricingDonations_IsFeatured" ON public."PricingDonations" USING btree ("IsFeatured");


--
-- Name: IX_PricingSponsors_GivingId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_PricingSponsors_GivingId" ON public."PricingSponsors" USING btree ("GivingId");


--
-- Name: IX_PricingSponsors_IsActive; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_PricingSponsors_IsActive" ON public."PricingSponsors" USING btree ("IsActive");


--
-- Name: IX_PricingSponsors_IsRelevant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_PricingSponsors_IsRelevant" ON public."PricingSponsors" USING btree ("IsRelevant");


--
-- Name: IX_RequestAdoptions_CreatedAt; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RequestAdoptions_CreatedAt" ON public."RequestAdoptions" USING btree ("CreatedAt");


--
-- Name: IX_RequestAdoptions_PetId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RequestAdoptions_PetId" ON public."RequestAdoptions" USING btree ("PetId");


--
-- Name: IX_RequestAdoptions_ReviewedBy; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RequestAdoptions_ReviewedBy" ON public."RequestAdoptions" USING btree ("ReviewedBy");


--
-- Name: IX_RequestAdoptions_Status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RequestAdoptions_Status" ON public."RequestAdoptions" USING btree ("Status");


--
-- Name: IX_RequestAdoptions_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RequestAdoptions_UserId" ON public."RequestAdoptions" USING btree ("UserId");


--
-- Name: IX_RequestDonations_CreatedAt; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RequestDonations_CreatedAt" ON public."RequestDonations" USING btree ("CreatedAt");


--
-- Name: IX_RequestDonations_PlanDonationId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RequestDonations_PlanDonationId" ON public."RequestDonations" USING btree ("PlanDonationId");


--
-- Name: IX_RequestDonations_Provider; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RequestDonations_Provider" ON public."RequestDonations" USING btree ("Provider");


--
-- Name: IX_RequestDonations_ReviewedBy; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RequestDonations_ReviewedBy" ON public."RequestDonations" USING btree ("ReviewedBy");


--
-- Name: IX_RequestDonations_Status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RequestDonations_Status" ON public."RequestDonations" USING btree ("Status");


--
-- Name: IX_RequestDonations_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RequestDonations_UserId" ON public."RequestDonations" USING btree ("UserId");


--
-- Name: IX_RequestSponsors_Mode; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RequestSponsors_Mode" ON public."RequestSponsors" USING btree ("Mode");


--
-- Name: IX_RequestSponsors_PetId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RequestSponsors_PetId" ON public."RequestSponsors" USING btree ("PetId");


--
-- Name: IX_RequestSponsors_PlanSponsorId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RequestSponsors_PlanSponsorId" ON public."RequestSponsors" USING btree ("PlanSponsorId");


--
-- Name: IX_RequestSponsors_ReviewedBy; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RequestSponsors_ReviewedBy" ON public."RequestSponsors" USING btree ("ReviewedBy");


--
-- Name: IX_RequestSponsors_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RequestSponsors_UserId" ON public."RequestSponsors" USING btree ("UserId");


--
-- Name: IX_RequestVolunteers_CreatedAt; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RequestVolunteers_CreatedAt" ON public."RequestVolunteers" USING btree ("CreatedAt");


--
-- Name: IX_RequestVolunteers_RequestDate; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RequestVolunteers_RequestDate" ON public."RequestVolunteers" USING btree ("RequestDate");


--
-- Name: IX_RequestVolunteers_ReviewedBy; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RequestVolunteers_ReviewedBy" ON public."RequestVolunteers" USING btree ("ReviewedBy");


--
-- Name: IX_RequestVolunteers_Status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RequestVolunteers_Status" ON public."RequestVolunteers" USING btree ("Status");


--
-- Name: IX_RequestVolunteers_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RequestVolunteers_UserId" ON public."RequestVolunteers" USING btree ("UserId");


--
-- Name: IX_RequestVolunteers_VolunteerApplicationId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RequestVolunteers_VolunteerApplicationId" ON public."RequestVolunteers" USING btree ("VolunteerApplicationId");


--
-- Name: IX_RolePermissions_PermissionId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RolePermissions_PermissionId" ON public."RolePermissions" USING btree ("PermissionId");


--
-- Name: IX_Species_Name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Species_Name" ON public."Species" USING btree ("Name");


--
-- Name: IX_SponsorFollowUps_SponsorId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_SponsorFollowUps_SponsorId" ON public."SponsorFollowUps" USING btree ("SponsorId");


--
-- Name: IX_Sponsors_RequestSponsorId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Sponsors_RequestSponsorId" ON public."Sponsors" USING btree ("RequestSponsorId");


--
-- Name: IX_Users_Email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Users_Email" ON public."Users" USING btree ("Email");


--
-- Name: IX_Users_RoleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Users_RoleId" ON public."Users" USING btree ("RoleId");


--
-- Name: IX_VolunteerApplications_CreatedAt; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_VolunteerApplications_CreatedAt" ON public."VolunteerApplications" USING btree ("CreatedAt");


--
-- Name: IX_VolunteerApplications_EndDate; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_VolunteerApplications_EndDate" ON public."VolunteerApplications" USING btree ("EndDate");


--
-- Name: IX_VolunteerApplications_IsCertified; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_VolunteerApplications_IsCertified" ON public."VolunteerApplications" USING btree ("IsCertified");


--
-- Name: IX_VolunteerApplications_StartDate; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_VolunteerApplications_StartDate" ON public."VolunteerApplications" USING btree ("StartDate");


--
-- Name: IX_VolunteerApplications_Urgency; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_VolunteerApplications_Urgency" ON public."VolunteerApplications" USING btree ("Urgency");


--
-- Name: IX_Volunteers_RequestVolunteerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Volunteers_RequestVolunteerId" ON public."Volunteers" USING btree ("RequestVolunteerId");


--
-- Name: AdoptionFollowUps FK_AdoptionFollowUps_Adoptions_AdoptionId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AdoptionFollowUps"
    ADD CONSTRAINT "FK_AdoptionFollowUps_Adoptions_AdoptionId" FOREIGN KEY ("AdoptionId") REFERENCES public."Adoptions"("Id") ON DELETE CASCADE;


--
-- Name: Adoptions FK_Adoptions_RequestAdoptions_RequestAdoptionId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Adoptions"
    ADD CONSTRAINT "FK_Adoptions_RequestAdoptions_RequestAdoptionId" FOREIGN KEY ("RequestAdoptionId") REFERENCES public."RequestAdoptions"("Id") ON DELETE CASCADE;


--
-- Name: Breeds FK_Breeds_Species_SpeciesId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Breeds"
    ADD CONSTRAINT "FK_Breeds_Species_SpeciesId" FOREIGN KEY ("SpeciesId") REFERENCES public."Species"("Id") ON DELETE RESTRICT;


--
-- Name: DonationFollowUps FK_DonationFollowUps_Donations_DonationId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DonationFollowUps"
    ADD CONSTRAINT "FK_DonationFollowUps_Donations_DonationId" FOREIGN KEY ("DonationId") REFERENCES public."Donations"("Id") ON DELETE CASCADE;


--
-- Name: Donations FK_Donations_RequestDonations_RequestDonationId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Donations"
    ADD CONSTRAINT "FK_Donations_RequestDonations_RequestDonationId" FOREIGN KEY ("RequestDonationId") REFERENCES public."RequestDonations"("Id") ON DELETE RESTRICT;


--
-- Name: MedicalRecords FK_MedicalRecords_Pets_PetId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MedicalRecords"
    ADD CONSTRAINT "FK_MedicalRecords_Pets_PetId" FOREIGN KEY ("PetId") REFERENCES public."Pets"("Id") ON DELETE CASCADE;


--
-- Name: PaymentHistories FK_PaymentHistories_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PaymentHistories"
    ADD CONSTRAINT "FK_PaymentHistories_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE RESTRICT;


--
-- Name: PetBreeds FK_PetBreeds_Breeds_BreedId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PetBreeds"
    ADD CONSTRAINT "FK_PetBreeds_Breeds_BreedId" FOREIGN KEY ("BreedId") REFERENCES public."Breeds"("Id") ON DELETE RESTRICT;


--
-- Name: PetBreeds FK_PetBreeds_Breeds_BreedId1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PetBreeds"
    ADD CONSTRAINT "FK_PetBreeds_Breeds_BreedId1" FOREIGN KEY ("BreedId1") REFERENCES public."Breeds"("Id");


--
-- Name: PetBreeds FK_PetBreeds_Pets_PetId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PetBreeds"
    ADD CONSTRAINT "FK_PetBreeds_Pets_PetId" FOREIGN KEY ("PetId") REFERENCES public."Pets"("Id") ON DELETE CASCADE;


--
-- Name: PetPhotos FK_PetPhotos_Pets_PetId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PetPhotos"
    ADD CONSTRAINT "FK_PetPhotos_Pets_PetId" FOREIGN KEY ("PetId") REFERENCES public."Pets"("Id") ON DELETE CASCADE;


--
-- Name: PetSponsors FK_PetSponsors_Pets_PetId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PetSponsors"
    ADD CONSTRAINT "FK_PetSponsors_Pets_PetId" FOREIGN KEY ("PetId") REFERENCES public."Pets"("Id") ON DELETE RESTRICT;


--
-- Name: PetSponsors FK_PetSponsors_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PetSponsors"
    ADD CONSTRAINT "FK_PetSponsors_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE RESTRICT;


--
-- Name: PetTraits FK_PetTraits_Pets_PetId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PetTraits"
    ADD CONSTRAINT "FK_PetTraits_Pets_PetId" FOREIGN KEY ("PetId") REFERENCES public."Pets"("Id") ON DELETE CASCADE;


--
-- Name: PetTraits FK_PetTraits_Traits_TraitId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PetTraits"
    ADD CONSTRAINT "FK_PetTraits_Traits_TraitId" FOREIGN KEY ("TraitId") REFERENCES public."Traits"("Id") ON DELETE RESTRICT;


--
-- Name: PetTraits FK_PetTraits_Traits_TraitId1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PetTraits"
    ADD CONSTRAINT "FK_PetTraits_Traits_TraitId1" FOREIGN KEY ("TraitId1") REFERENCES public."Traits"("Id");


--
-- Name: PetVaccines FK_PetVaccines_Pets_PetId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PetVaccines"
    ADD CONSTRAINT "FK_PetVaccines_Pets_PetId" FOREIGN KEY ("PetId") REFERENCES public."Pets"("Id") ON DELETE CASCADE;


--
-- Name: PetVaccines FK_PetVaccines_Vacines_VaccineId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PetVaccines"
    ADD CONSTRAINT "FK_PetVaccines_Vacines_VaccineId" FOREIGN KEY ("VaccineId") REFERENCES public."Vacines"("Id") ON DELETE RESTRICT;


--
-- Name: Pets FK_Pets_Species_SpeciesId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Pets"
    ADD CONSTRAINT "FK_Pets_Species_SpeciesId" FOREIGN KEY ("SpeciesId") REFERENCES public."Species"("Id") ON DELETE RESTRICT;


--
-- Name: PricingDonations FK_PricingDonations_Givings_GivingId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PricingDonations"
    ADD CONSTRAINT "FK_PricingDonations_Givings_GivingId" FOREIGN KEY ("GivingId") REFERENCES public."Givings"("Id") ON DELETE CASCADE;


--
-- Name: PricingSponsors FK_PricingSponsors_Givings_GivingId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PricingSponsors"
    ADD CONSTRAINT "FK_PricingSponsors_Givings_GivingId" FOREIGN KEY ("GivingId") REFERENCES public."Givings"("Id") ON DELETE CASCADE;


--
-- Name: RequestAdoptions FK_RequestAdoptions_Pets_PetId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RequestAdoptions"
    ADD CONSTRAINT "FK_RequestAdoptions_Pets_PetId" FOREIGN KEY ("PetId") REFERENCES public."Pets"("Id") ON DELETE SET NULL;


--
-- Name: RequestAdoptions FK_RequestAdoptions_Users_ReviewedBy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RequestAdoptions"
    ADD CONSTRAINT "FK_RequestAdoptions_Users_ReviewedBy" FOREIGN KEY ("ReviewedBy") REFERENCES public."Users"("Id") ON DELETE SET NULL;


--
-- Name: RequestAdoptions FK_RequestAdoptions_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RequestAdoptions"
    ADD CONSTRAINT "FK_RequestAdoptions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: RequestDonations FK_RequestDonations_PricingDonations_PlanDonationId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RequestDonations"
    ADD CONSTRAINT "FK_RequestDonations_PricingDonations_PlanDonationId" FOREIGN KEY ("PlanDonationId") REFERENCES public."PricingDonations"("Id") ON DELETE SET NULL;


--
-- Name: RequestDonations FK_RequestDonations_Users_ReviewedBy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RequestDonations"
    ADD CONSTRAINT "FK_RequestDonations_Users_ReviewedBy" FOREIGN KEY ("ReviewedBy") REFERENCES public."Users"("Id") ON DELETE SET NULL;


--
-- Name: RequestDonations FK_RequestDonations_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RequestDonations"
    ADD CONSTRAINT "FK_RequestDonations_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: RequestSponsors FK_RequestSponsors_Pets_PetId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RequestSponsors"
    ADD CONSTRAINT "FK_RequestSponsors_Pets_PetId" FOREIGN KEY ("PetId") REFERENCES public."Pets"("Id") ON DELETE CASCADE;


--
-- Name: RequestSponsors FK_RequestSponsors_PricingSponsors_PlanSponsorId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RequestSponsors"
    ADD CONSTRAINT "FK_RequestSponsors_PricingSponsors_PlanSponsorId" FOREIGN KEY ("PlanSponsorId") REFERENCES public."PricingSponsors"("Id") ON DELETE SET NULL;


--
-- Name: RequestSponsors FK_RequestSponsors_Users_ReviewedBy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RequestSponsors"
    ADD CONSTRAINT "FK_RequestSponsors_Users_ReviewedBy" FOREIGN KEY ("ReviewedBy") REFERENCES public."Users"("Id") ON DELETE SET NULL;


--
-- Name: RequestSponsors FK_RequestSponsors_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RequestSponsors"
    ADD CONSTRAINT "FK_RequestSponsors_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: RequestVolunteers FK_RequestVolunteers_Users_ReviewedBy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RequestVolunteers"
    ADD CONSTRAINT "FK_RequestVolunteers_Users_ReviewedBy" FOREIGN KEY ("ReviewedBy") REFERENCES public."Users"("Id") ON DELETE SET NULL;


--
-- Name: RequestVolunteers FK_RequestVolunteers_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RequestVolunteers"
    ADD CONSTRAINT "FK_RequestVolunteers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE RESTRICT;


--
-- Name: RequestVolunteers FK_RequestVolunteers_VolunteerApplications_VolunteerApplicatio~; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RequestVolunteers"
    ADD CONSTRAINT "FK_RequestVolunteers_VolunteerApplications_VolunteerApplicatio~" FOREIGN KEY ("VolunteerApplicationId") REFERENCES public."VolunteerApplications"("Id") ON DELETE CASCADE;


--
-- Name: RolePermissions FK_RolePermissions_Permissions_PermissionId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RolePermissions"
    ADD CONSTRAINT "FK_RolePermissions_Permissions_PermissionId" FOREIGN KEY ("PermissionId") REFERENCES public."Permissions"("Id") ON DELETE CASCADE;


--
-- Name: RolePermissions FK_RolePermissions_Roles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RolePermissions"
    ADD CONSTRAINT "FK_RolePermissions_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."Roles"("Id") ON DELETE CASCADE;


--
-- Name: SponsorFollowUps FK_SponsorFollowUps_Sponsors_SponsorId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SponsorFollowUps"
    ADD CONSTRAINT "FK_SponsorFollowUps_Sponsors_SponsorId" FOREIGN KEY ("SponsorId") REFERENCES public."Sponsors"("Id") ON DELETE CASCADE;


--
-- Name: Sponsors FK_Sponsors_RequestSponsors_RequestSponsorId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Sponsors"
    ADD CONSTRAINT "FK_Sponsors_RequestSponsors_RequestSponsorId" FOREIGN KEY ("RequestSponsorId") REFERENCES public."RequestSponsors"("Id") ON DELETE RESTRICT;


--
-- Name: Users FK_Users_Roles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."Roles"("Id") ON DELETE RESTRICT;


--
-- Name: Volunteers FK_Volunteers_RequestVolunteers_RequestVolunteerId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Volunteers"
    ADD CONSTRAINT "FK_Volunteers_RequestVolunteers_RequestVolunteerId" FOREIGN KEY ("RequestVolunteerId") REFERENCES public."RequestVolunteers"("Id") ON DELETE CASCADE;
